class Config:
    page_url = ''
    page_testPageUrl = ''
    driver_path = ''
    secure_email = ''
    password = ''
    secure_email_second = ''
    password_second = ''
    unregistered_email = ''
    wrong_password = ''
    without_alternative_email = ''
    alternative_email_for_secure = ''
    unprotected_email = ''
    alternative_email_for_unprotected = ''
    email_subject_empty = ''
    email_body = ''